### ISSUE TITLE
Add link to data dictionary above "View Data Summary" link

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-data-browser#78]
We want to add this as a link so users know what they're expecting in terms of the data fields available before downloading the datasets.

**Comment by wpears** [comment]
Is this in addition to the link included in the description below the main page header? Is it a link to the same place? If it is indeed another link to the data dictionary pdf, it seems like it might be more appropriate near the actual csv download buttons, rather than the view data summary button. Alternatively if people are having trouble understanding the data in the aggregation table, it could be placed near the header there once it's generated.

**Comment by chynnakeys** [comment]
@wpears I get what you're saying. I think we can go with what you said, and see if testers make any comments.
